/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordering.system;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROG
 */
public class manage_account extends javax.swing.JFrame {

    /**
     * Creates new form manage_account
     */
    public manage_account() {
        initComponents();
        // set the JFrame to center position
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        role_combo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        account_table = new javax.swing.JTable();
        back_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        username_txtField = new javax.swing.JTextField();
        password_txtField = new javax.swing.JPasswordField();
        email_txtField = new javax.swing.JTextField();
        contact_txtField = new javax.swing.JTextField();
        age_txtField = new javax.swing.JTextField();
        address_txtField = new javax.swing.JTextField();
        modify_button = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        male_rbutton = new javax.swing.JRadioButton();
        female_rbutton = new javax.swing.JRadioButton();
        id_txtField = new javax.swing.JLabel();
        delete_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel1.setText("Manage Account Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        role_combo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        role_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Select Role ---", "Customer", "Manager" }));
        role_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role_comboActionPerformed(evt);
            }
        });

        account_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Password", "Role", "Username", "Email", "Contact", "Gender", "Age", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        account_table.getTableHeader().setReorderingAllowed(false);
        account_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                account_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(account_table);
        if (account_table.getColumnModel().getColumnCount() > 0) {
            account_table.getColumnModel().getColumn(0).setResizable(false);
            account_table.getColumnModel().getColumn(0).setPreferredWidth(50);
            account_table.getColumnModel().getColumn(3).setResizable(false);
            account_table.getColumnModel().getColumn(3).setPreferredWidth(90);
            account_table.getColumnModel().getColumn(4).setResizable(false);
            account_table.getColumnModel().getColumn(4).setPreferredWidth(150);
            account_table.getColumnModel().getColumn(5).setResizable(false);
            account_table.getColumnModel().getColumn(5).setPreferredWidth(90);
        }

        back_button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Username:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Password:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Email:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Contact Number:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Gender:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Address:");

        password_txtField.setText("jPasswordField1");
        password_txtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                password_txtFieldMouseClicked(evt);
            }
        });

        modify_button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        modify_button.setText("Update");
        modify_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_buttonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Age:");

        gender_group.add(male_rbutton);
        male_rbutton.setText("Male");

        gender_group.add(female_rbutton);
        female_rbutton.setText("Female");

        id_txtField.setForeground(java.awt.Color.white);

        delete_button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modify_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_button)
                .addGap(11, 11, 11))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(id_txtField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(28, 28, 28)
                                .addComponent(male_rbutton)
                                .addGap(18, 18, 18)
                                .addComponent(female_rbutton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(age_txtField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contact_txtField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username_txtField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password_txtField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email_txtField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(username_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(password_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addComponent(email_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(contact_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(male_rbutton)
                    .addComponent(female_rbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(address_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(modify_button)
                        .addComponent(delete_button))
                    .addComponent(id_txtField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(back_button)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(role_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(357, 357, 357))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(role_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // role JComboBox : manager/customer
    private void role_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role_comboActionPerformed
        // TODO add your handling code here:
        username_txtField.setText(null);
        password_txtField.setText(null);
        email_txtField.setText(null);
        contact_txtField.setText(null);
        gender_group.clearSelection();
        age_txtField.setText(null);
        address_txtField.setText(null);
        DefaultTableModel model = (DefaultTableModel) account_table.getModel();
        while(account_table.getRowCount()!=0){
            model.removeRow(0);
        }
        // open user.txt file
        File file = new File("user.txt");
        try {
            BufferedReader tr = new BufferedReader (new FileReader(file));
            Object[] tableLines = tr.lines().toArray();
            for(int i = 0; i <tableLines.length;i++)
            {
                String line = tableLines[i].toString().trim();
                // if JComboBox was selected, it will shows the details of the role
                if(line.contains((String) role_combo.getSelectedItem())){                
                    String[] dataRow = line.split(",");
                    model.addRow(dataRow);                 
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(manage_account.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(manage_account.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_role_comboActionPerformed

    // back to manage account menu
    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        manageAcc_menu mm = new manageAcc_menu();
        mm.setVisible(true);
    }//GEN-LAST:event_back_buttonActionPerformed

    // set password text field to null when mouse clicked
    private void password_txtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_txtFieldMouseClicked
        // TODO add your handling code here:
        password_txtField.setText(null);
    }//GEN-LAST:event_password_txtFieldMouseClicked

    // update button
    private void modify_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify_buttonActionPerformed
        // TODO add your handling code here:
        
        // define new variables to update
        String editID = id_txtField.getText();
        String new_gender = null;
        String new_username = username_txtField.getText();
        String new_password = password_txtField.getText();
        String new_email = email_txtField.getText();
        String new_contact = contact_txtField.getText();
        if (male_rbutton.isSelected())
        {
            new_gender = "Male";
        }
        else if (female_rbutton.isSelected())
        {
            new_gender = "Female";
        }
        String new_age = age_txtField.getText();
        String new_address = address_txtField.getText();

        ArrayList<String> tempCustomer = new ArrayList<>();
        try {
            try
            {
                FileReader fr = new FileReader("user.txt");
                Scanner reader = new Scanner (fr);

                String line;
                while((line=reader.nextLine())!=null) {
                    String[] data = line.split(",");
                    // temporarily store in "tempCustomer" array list
                    if (data[0].equals(editID)) {
                        tempCustomer.add(
                            data[0]+","+
                            new_password+","+
                            data[2]+","+
                            new_username+","+
                            new_email+","+
                            new_contact+","+
                            new_gender+","+
                            new_age+","+
                            new_address);

                        JOptionPane.showMessageDialog(this, "Successfully Updated");
                        this.dispose();
                        manageAcc_menu mm = new manageAcc_menu();
                        mm.setVisible(true);
                    }
                    else
                    {
                        tempCustomer.add(line);
                    }
                }
                fr.close();
            }
            catch(Exception e){
                // JOptionPane.showMessageDialog(this, "Error","Error Box",JOptionPane.ERROR_MESSAGE);;
            }
            try {
                // overwrite user.txt file after update the specific row
                PrintWriter fw = new PrintWriter("user.txt");

                for(String str : tempCustomer){
                    fw.println(str);
                }
                fw.close();
            } catch(Exception e){
                // JOptionPane.showMessageDialog(this, "Error","Error Box",JOptionPane.ERROR_MESSAGE);;
            }
        } catch(Exception e) {
            // JOptionPane.showMessageDialog(this, "Error","Error Box",JOptionPane.ERROR_MESSAGE);;
        }

    }//GEN-LAST:event_modify_buttonActionPerformed

    // delete button
    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        String deleteID = id_txtField.getText();
                
        ArrayList<String> tempCustomer = new ArrayList<>();
        try {
            try
            {
                FileReader fr = new FileReader("user.txt");
                Scanner reader = new Scanner (fr);

                String line;
                while((line=reader.nextLine())!=null) {
                    String[] data = line.split(",");
                    if (data[0].equals(deleteID)) {
                        JOptionPane.showMessageDialog(this, "Successfully Deleted");
                        this.dispose();
                        manageAcc_menu mm = new manageAcc_menu();
                        mm.setVisible(true);
                    }
                    else
                    {
                        tempCustomer.add(line);
                    }
                }
                fr.close();
            }
            catch(Exception e){
                // JOptionPane.showMessageDialog(this, "Error","Error Box",JOptionPane.ERROR_MESSAGE);;
            }
            // overwrite user.txt file after delete the specific row
            try {
                PrintWriter fw = new PrintWriter("user.txt");

                for(String str : tempCustomer){
                    fw.println(str);
                }
                fw.close();
            } catch(Exception e){
                // JOptionPane.showMessageDialog(this, "Error","Error Box",JOptionPane.ERROR_MESSAGE);;
            }
        } catch(Exception e) {
            // JOptionPane.showMessageDialog(this, "Error","Error Box",JOptionPane.ERROR_MESSAGE);;
        }
    }//GEN-LAST:event_delete_buttonActionPerformed

    // fill in the specific data when the JTable row was selected
    private void account_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_account_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)account_table.getModel();
        int selectedRowIndex = account_table.getSelectedRow();
        
        String gender = model.getValueAt(selectedRowIndex, 6).toString();
        if (gender.equals("Male")) {
            male_rbutton.setSelected(true);
        }
        else {
            female_rbutton.setSelected(true);
        }
        username_txtField.setText(model.getValueAt(selectedRowIndex, 3).toString());
        password_txtField.setText(model.getValueAt(selectedRowIndex, 1).toString());
        email_txtField.setText(model.getValueAt(selectedRowIndex, 4).toString());
        contact_txtField.setText(model.getValueAt(selectedRowIndex, 5).toString());
        age_txtField.setText(model.getValueAt(selectedRowIndex, 7).toString());
        address_txtField.setText(model.getValueAt(selectedRowIndex, 8).toString());
        id_txtField.setText(model.getValueAt(selectedRowIndex, 0).toString());
        id_txtField.setVisible(false);
    }//GEN-LAST:event_account_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable account_table;
    private javax.swing.JTextField address_txtField;
    private javax.swing.JTextField age_txtField;
    private javax.swing.JButton back_button;
    private javax.swing.JTextField contact_txtField;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField email_txtField;
    private javax.swing.JRadioButton female_rbutton;
    private javax.swing.ButtonGroup gender_group;
    private javax.swing.JLabel id_txtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male_rbutton;
    private javax.swing.JButton modify_button;
    private javax.swing.JPasswordField password_txtField;
    private javax.swing.JComboBox<String> role_combo;
    private javax.swing.JTextField username_txtField;
    // End of variables declaration//GEN-END:variables
}
