/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordering.system;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author ROG
 */
public class registration_form extends javax.swing.JFrame {
    /**
     * Creates new form registration_form
     */
    public registration_form() {
        initComponents();
        // set the JFrame to center position
        this.setLocationRelativeTo(null);
        // disable the button or text field
        submit_button.setEnabled(false);
        confirmpass_txtField.setEnabled(false);
        id_txtField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender_group = new javax.swing.ButtonGroup();
        role_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        username_txtField = new javax.swing.JTextField();
        email_txtField = new javax.swing.JTextField();
        contact_txtField = new javax.swing.JTextField();
        male_rButton = new javax.swing.JRadioButton();
        female_rButton = new javax.swing.JRadioButton();
        age_txtField = new javax.swing.JTextField();
        pass_txtField = new javax.swing.JPasswordField();
        confirmpass_txtField = new javax.swing.JPasswordField();
        address_txtField = new javax.swing.JTextField();
        submit_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        id_txtField = new javax.swing.JTextField();
        nlab = new javax.swing.JLabel();
        nlab1 = new javax.swing.JLabel();
        nlab2 = new javax.swing.JLabel();
        nlab3 = new javax.swing.JLabel();
        nlab4 = new javax.swing.JLabel();
        nlab5 = new javax.swing.JLabel();
        nlab6 = new javax.swing.JLabel();
        nlab7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        customer_rButton = new javax.swing.JRadioButton();
        manager_rButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel1.setText("Registration Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Contact Number:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Age:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Password:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Confirm Password:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Address:");

        username_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                username_txtFieldKeyReleased(evt);
            }
        });

        email_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                email_txtFieldKeyReleased(evt);
            }
        });

        contact_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contact_txtFieldKeyReleased(evt);
            }
        });

        gender_group.add(male_rButton);
        male_rButton.setText("Male");

        gender_group.add(female_rButton);
        female_rButton.setText("Female");

        age_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                age_txtFieldKeyReleased(evt);
            }
        });

        pass_txtField.setText("jPasswordField1");
        pass_txtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass_txtFieldMouseClicked(evt);
            }
        });
        pass_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pass_txtFieldKeyReleased(evt);
            }
        });

        confirmpass_txtField.setText("jPasswordField1");
        confirmpass_txtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmpass_txtFieldMouseClicked(evt);
            }
        });
        confirmpass_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmpass_txtFieldKeyReleased(evt);
            }
        });

        address_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                address_txtFieldKeyReleased(evt);
            }
        });

        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("ID:");

        id_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_txtFieldKeyReleased(evt);
            }
        });

        nlab.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        nlab.setForeground(java.awt.Color.red);

        nlab1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        nlab1.setForeground(java.awt.Color.red);

        nlab2.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        nlab2.setForeground(java.awt.Color.red);

        nlab3.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        nlab3.setForeground(java.awt.Color.red);

        nlab4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        nlab4.setForeground(java.awt.Color.red);

        nlab5.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        nlab5.setForeground(java.awt.Color.red);

        nlab6.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        nlab6.setForeground(java.awt.Color.red);

        nlab7.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        nlab7.setForeground(java.awt.Color.red);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Role: ");

        role_group.add(customer_rButton);
        customer_rButton.setText("Customer");
        customer_rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_rButtonActionPerformed(evt);
            }
        });

        role_group.add(manager_rButton);
        manager_rButton.setText("Manager");
        manager_rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manager_rButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submit_button)
                        .addGap(18, 18, 18)
                        .addComponent(cancel_button)
                        .addGap(18, 18, 18)
                        .addComponent(back_button))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(email_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(80, 80, 80)
                                .addComponent(username_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contact_txtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(male_rButton)
                                        .addGap(31, 31, 31)
                                        .addComponent(female_rButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(age_txtField)
                                    .addComponent(pass_txtField)
                                    .addComponent(confirmpass_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(90, 90, 90)
                                .addComponent(address_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(121, 121, 121)
                                .addComponent(id_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel8)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(107, 107, 107)
                            .addComponent(customer_rButton)
                            .addGap(16, 16, 16)
                            .addComponent(manager_rButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nlab, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(nlab1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(nlab6, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(nlab5, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(nlab4, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(nlab3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(nlab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(nlab7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nlab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(username_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel3)
                                                    .addComponent(nlab1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(email_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(nlab2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(contact_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(male_rButton)
                                            .addComponent(female_rButton))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addComponent(nlab3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(age_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(pass_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nlab4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nlab5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(confirmpass_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(address_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nlab6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(customer_rButton)
                    .addComponent(manager_rButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(id_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nlab7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_button)
                    .addComponent(back_button)
                    .addComponent(cancel_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // clear all text field to null
    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        username_txtField.setText(null);
        email_txtField.setText(null);
        contact_txtField.setText(null);
        age_txtField.setText(null);
        pass_txtField.setText("*********");
        confirmpass_txtField.setText("*********");
        address_txtField.setText(null);
        submit_button.setEnabled(false);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    // submit button
    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
        // define login page as lg
        Login lg = new Login();
        String gender = null;
        try {
            File f = new File("user.txt");
            BufferedWriter bw = new BufferedWriter(new FileWriter(f,true));
            BufferedReader br = new BufferedReader (new FileReader(f));
            if (male_rButton.isSelected()) {
                gender = "Male";
            } else if (female_rButton.isSelected()) {
                gender = "Female";
            }
            // write all information to user.txt
            if (customer_rButton.isSelected()) {
                Customer cs = new Customer(username_txtField.getText(), email_txtField.getText(), contact_txtField.getText(), gender, age_txtField.getText(), confirmpass_txtField.getText(), address_txtField.getText());
                bw.write(cs.getCustomerID()+id_txtField.getText()+","+cs.getPassword()+","+cs.getCustomerRole()+","+cs.getName()+","+cs.getEmail()+","+cs.getContact()+","+cs.getGender()+","+cs.getAge()+","+cs.getAddress()+"\n");
                bw.close();
                JOptionPane.showMessageDialog(this, "Successful Register");
                lg.setVisible(true);
                this.dispose(); 
             }
             else if (manager_rButton.isSelected()) {
                Manager mg = new Manager(username_txtField.getText(), email_txtField.getText(), contact_txtField.getText(), gender, age_txtField.getText(), confirmpass_txtField.getText(), address_txtField.getText());
                bw.write(mg.getManagerID()+id_txtField.getText()+","+mg.getPassword()+","+mg.getManagerRole()+","+mg.getName()+","+mg.getEmail()+","+mg.getContact()+","+mg.getGender()+","+mg.getAge()+","+mg.getAddress()+"\n");
                bw.close();
                JOptionPane.showMessageDialog(this, "Successful Register");
                lg.setVisible(true);
                this.dispose(); 
             }
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error","Error Box",JOptionPane.ERROR_MESSAGE);;
        }
    }//GEN-LAST:event_submit_buttonActionPerformed

    // password text field set to null when mouse clicked
    private void pass_txtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass_txtFieldMouseClicked
        // TODO add your handling code here:
        pass_txtField.setText(null);
    }//GEN-LAST:event_pass_txtFieldMouseClicked

    // confirm password text field set to null when mouse clicked
    private void confirmpass_txtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmpass_txtFieldMouseClicked
        // TODO add your handling code here:
        confirmpass_txtField.setText(null);
    }//GEN-LAST:event_confirmpass_txtFieldMouseClicked

    // username validation
    private void username_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtFieldKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9 ]{1,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match=patt.matcher(username_txtField.getText());
        if(!match.matches()){
            nlab.setText("Naming is incorrect!");
        }
        else{
            nlab.setText(null);
        }
    }//GEN-LAST:event_username_txtFieldKeyReleased

    // email validation
    private void email_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_txtFieldKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{1,30}[@][a-zA-z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match=patt.matcher(email_txtField.getText());
        if(!match.matches()){
            nlab1.setText("Email is incorrect!");
        }
        else{
            nlab1.setText(null);
        }
    }//GEN-LAST:event_email_txtFieldKeyReleased

    // contact number validation
    private void contact_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact_txtFieldKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[+601][0-9]{3,11}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match=patt.matcher(contact_txtField.getText());
        if(!match.matches()){
            nlab2.setText("Contact is incorrect! +60112345678");
        }
        else{
            nlab2.setText(null);
        }
    }//GEN-LAST:event_contact_txtFieldKeyReleased

    // age validation
    private void age_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_txtFieldKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[1-9][0-9]{0,1}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(age_txtField.getText());
        if (!match.matches()) {
            nlab3.setText("Age is incorrect!");
        }
        else {
            nlab3.setText(null);
        }
    }//GEN-LAST:event_age_txtFieldKeyReleased

    // password validation
    private void pass_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_txtFieldKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9A-Za-z]{8,12}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match=patt.matcher(pass_txtField.getText());
        if(!match.matches()){
            nlab4.setText("Password Lenght Must be at least 8 digit");
        }
        else{
            nlab4.setText(null);
            confirmpass_txtField.setEnabled(true);
        }
    }//GEN-LAST:event_pass_txtFieldKeyReleased

    // confirm password validation
    private void confirmpass_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmpass_txtFieldKeyReleased
        // TODO add your handling code here:
        if(!pass_txtField.getText().equals(confirmpass_txtField.getText())) {
            nlab5.setText("Passowrd is not match");
        }
        else
        {
            nlab5.setText(null);
        }
    }//GEN-LAST:event_confirmpass_txtFieldKeyReleased

    // address validation
    private void address_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_address_txtFieldKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9, ]{1,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match=patt.matcher(address_txtField.getText());
        if(!match.matches()){
            nlab6.setText("Address is incorrect!");
        }
        else{
            nlab6.setText(null);
        }
    }//GEN-LAST:event_address_txtFieldKeyReleased

    // back to login page
    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    // role radio button : customer
    private void customer_rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_rButtonActionPerformed
        // TODO add your handling code here:
        customer_rButton.isSelected();
        id_txtField.setEnabled(true);
        id_txtField.setText(null);
        nlab7.setText(null);
    }//GEN-LAST:event_customer_rButtonActionPerformed

    // role radio button : manager
    private void manager_rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manager_rButtonActionPerformed
        // TODO add your handling code here:
        manager_rButton.isSelected();
        id_txtField.setEnabled(true);
        id_txtField.setText(null);
        nlab7.setText(null);
    }//GEN-LAST:event_manager_rButtonActionPerformed

    // id validation
    private void id_txtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_txtFieldKeyReleased
        // TODO add your handling code here:

        String line;
        File export_file = new File("user.txt");
        try
        {
            submit_button.setEnabled(true);
            String PATTERN="^[0-9]{3}[1-9]$";
            Pattern patt = Pattern.compile(PATTERN);
            Matcher match=patt.matcher(id_txtField.getText());
            BufferedReader br = new BufferedReader(new FileReader(export_file));
            while ((line = br.readLine()) != null) {
                String userData [] = line.split(",");
                if (customer_rButton.isSelected()) {
                    if(!match.matches()) {
                        nlab7.setText("It must be integer with 4 digit");
                        submit_button.setEnabled(false);
                    }
                    else if (userData[0].equals("C"+id_txtField.getText())) {
                        nlab7.setText("Customer ID Existed");
                        submit_button.setEnabled(false);
                        }
                    else {
                        nlab7.setText(null);
                        submit_button.setEnabled(true);
                    }
                }
                else if (manager_rButton.isSelected()) {
                    if(!match.matches()) {
                        nlab7.setText("It must be integer with 4 digit");
                        submit_button.setEnabled(false);
                    }
                    else if (userData[0].equals("M"+id_txtField.getText())) {
                        nlab7.setText("Manager ID Existed");
                        submit_button.setEnabled(false);
                        }
                    else {
                        nlab7.setText(null);
                        submit_button.setEnabled(true);
                    }
                }
            }
        }catch(IOException Ex){

        }
    }//GEN-LAST:event_id_txtFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_txtField;
    private javax.swing.JTextField age_txtField;
    private javax.swing.JButton back_button;
    private javax.swing.JButton cancel_button;
    private javax.swing.JPasswordField confirmpass_txtField;
    private javax.swing.JTextField contact_txtField;
    private javax.swing.JRadioButton customer_rButton;
    private javax.swing.JTextField email_txtField;
    private javax.swing.JRadioButton female_rButton;
    private javax.swing.ButtonGroup gender_group;
    private javax.swing.JTextField id_txtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male_rButton;
    private javax.swing.JRadioButton manager_rButton;
    private javax.swing.JLabel nlab;
    private javax.swing.JLabel nlab1;
    private javax.swing.JLabel nlab2;
    private javax.swing.JLabel nlab3;
    private javax.swing.JLabel nlab4;
    private javax.swing.JLabel nlab5;
    private javax.swing.JLabel nlab6;
    private javax.swing.JLabel nlab7;
    private javax.swing.JPasswordField pass_txtField;
    private javax.swing.ButtonGroup role_group;
    private javax.swing.JButton submit_button;
    private javax.swing.JTextField username_txtField;
    // End of variables declaration//GEN-END:variables
}
